CREATE TABLE IF NOT EXISTS "ADDRESS" (
	"ID" BIGINT NOT NULL,
	"COUNTRY" VARCHAR(255) NOT NULL,
	"CITY" VARCHAR(255) NOT NULL,
	"STREET" VARCHAR(255) NOT NULL,
	"POST_CODE" VARCHAR(255) NOT NULL,
	CONSTRAINT "ADDRESS_PKEY" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "PROJECT" (
	"ID" BIGINT NOT NULL,
	"TITLE" VARCHAR(255) NOT NULL,
	CONSTRAINT "PROJECT_PKEY" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "EMPLOYEE" (
	"ID" BIGINT NOT NULL,
	"FIRST_NAME" VARCHAR(255) NOT NULL,
	"LAST_NAME" VARCHAR(255) NOT NULL,
	"BIRTHDAY" DATE NOT NULL,
 	CONSTRAINT "EMPLOYEE_PKEY" PRIMARY KEY ("ID"),
	CONSTRAINT "EMPLOYEE_FKEY" FOREIGN KEY ("ID") REFERENCES "ADDRESS" ("ID")
);

CREATE TABLE IF NOT EXISTS "EMPL_PROJ" (
	"EMPLOYEE_ID" BIGINT NOT NULL,
	"PROJECT_ID" BIGINT NOT NULL,
	CONSTRAINT "EMPL_PROJ_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID")
		REFERENCES public."EMPLOYEE" ("ID"),
	CONSTRAINT "EMPL_PROJ_PROJECT_ID_fkey" FOREIGN KEY ("PROJECT_ID")
		REFERENCES "PROJECT" ("ID")
);

/*

INSERT INTO ADDRESS (ID, COUNTRY, CITY, STREET, POST_CODE) VALUES (1, 'Russia', 'Moscow', 'Red Square', '12345');

SELECT * FROM ADDRESS;
SELECT * FROM ADDRESS WHERE ID = 1;
UPDATE ADDRESS SET COUNTRY = ?, CITY = ?, STREET = ?, POST_CODE = ? WHERE ID = ?;
DELETE FROM ADDRESS WHERE ID = ?;

*/